<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;



    /**
     * In case you add more fields, don't forget to update src/Application/Sonata/UserBundle/Resources/config/doctrine/User.orm.xml
     * 
     * Uncomment setEmail and setEmailCanonical functions below to
     * set user's username as email address by default. Make sure
     * you remove username from registration and profile edit as well.
     */

    // public function setEmail($email){
    //     $this->email = $email;
    //     $this->username = $email;
    // }

    // public function setEmailCanonical($emailCanonical){
    //     $this->emailCanonical = $emailCanonical;
    //     $this->usernameCanonical = $emailCanonical;
    // }

}
